auto lo
iface lo inet loopback

iface ens33 inet manual

auto vmbr0
iface vmbr0 inet static
        address 192.168.40.132/24
        gateway 192.168.40.2
        bridge-ports ens33
        bridge-stp off
        bridge-fd 0
# WAN reel de l'hyperviseur (VMnet8 VMware NAT), simule Interne entre les firewalls

auto vmbr1
iface vmbr1 inet manual
        bridge-ports none
        bridge-stp off
        bridge-fd 0
# LAN Londres - postes (10.1.10.0/24)

auto vmbr2
iface vmbr2 inet manual
        bridge-ports none
        bridge-stp off
        bridge-fd 0
# LAN Londres - serveurs (10.1.20.0/24)

auto vmbr3
iface vmbr3 inet manual
        bridge-ports none
        bridge-stp off
        bridge-fd 0
# LAN Ponte-Vedra Beach USA (10.2.10.0/24)


auto vmbr4
iface vmbr4 inet manual
        bridge-ports none
        bridge-stp off
        bridge-fd 0
# LAN Sydney Australie (10.3.10.0/24)

auto vmbr5
iface vmbr5 inet manual
        bridge-ports none
        bridge-stp off
        bridge-fd 0
# LAN Monaco (10.4.10.0/24)

auto vmbr6
iface vmbr6 inet manual
        bridge-ports none
        bridge-stp off
        bridge-fd 0
# LAN PRA Monaco (10.1.20.0/24 - meme sous-reseau que Londre serveurs

auto vmbr7
iface vmbr7 inet manual
        bridge-ports none
        bridge-stp off
        bridge-fd 0
# LAN Datacenter Cloud Hebergeur (10.5.10.0/24)